// <auto-generated />
using DESUBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DESUBot.Migrations.RestorerolesMigrations
{
    [DbContext(typeof(Restoreroles))]
    [Migration("20181202013805_RestorerolesInitial")]
    partial class RestorerolesInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("DESUBot.Data.RestoreRoleModel", b =>
                {
                    b.Property<ulong>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("AdminID");

                    b.Property<string>("DateInserted");

                    b.Property<string>("Time");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.ToTable("RestoreRoles");
                });

            modelBuilder.Entity("DESUBot.Data.RestoreRoleModelRoles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("RoleID");

                    b.Property<string>("RoleName");

                    b.Property<ulong>("UserID");

                    b.HasKey("ID");

                    b.ToTable("RoleModelRolesStore");
                });
#pragma warning restore 612, 618
        }
    }
}
